=== Mcd0LUO/McFunction-Spirit-for-1.12.2/schemas/HelperConfig.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "HelperConfig",
    "description": "Minecraft Function Helper Configuration",
    "type": "object",
    "properties": {
        "ignore-function-directory": {
            "type": "array",
            "description": "需要忽略的函数目录列表",
            "items": {
                "type": "string"
            }
        },
        "ignore-advancement-directory": {
            "type": "array",
            "description": "需要忽略的进度目录列表",
            "items": {
                "type": "string"
            }
        },
        "space-auto-add": {
            "type": "boolean",
            "description": "是否在命令补全后自动添加空格",
            "default": true
        },
        "check-data-exists": {
            "type": "boolean",
            "description": "是否检查数据[记分板|函数]是否存在",
            "default": true
        },
        "check-scoreboard-length": {
            "type": "boolean",
            "description": "是否检查记分板长度",
            "default": true
        },
        "json-message-hover-preview": {
            "type": "boolean",
            "description": "是否在鼠标悬停时预览JSON消息",
            "default": true
        },
        "json-message-block-preview": {
            "type": "boolean",
            "description": "是否在代码后预览JSON消息",
            "default": true
        },
        "function-reference-preview": {
            "type": "boolean",
            "description": "是否在鼠标悬停时预览函数引用",
            "default": true
        }
    },
    "required": [
        "ignore-function-directory",
        "ignore-advancement-directory",
        "space-auto-add",
        "check-data-exists",
        "check-scoreboard-length",
        "json-message-hover-preview",
        "json-message-block-preview",
        "function-reference-preview"
    ],
    "additionalProperties": false
}

=== Mcd0LUO/McFunction-Spirit-for-1.12.2/HelperConfig.json
{
    "ignore-function-directory": [

    ],
    "ignore-advancement-directory": [
        
    ],
    "space-auto-add": true,
    "check-data-exists": true,
    "check-scoreboard-length": true,
    "json-message-hover-preview": true,
    "json-message-block-preview": true,
    "function-reference-preview": true
    
}
